###
# only users with admin role are allowed to access this endpoint
###
GET http://localhost:8080/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTY4NTczMTIwMiwiaWF0IjoxNjg1Njk1MjAyfQ.SHCV_yYqcdKSOMCrY4T-BmjtZX6OkEjCf0929CLNpCU

